export const CARDS_12 = [
	{ id: 1, value: 1, isHidden: true },
	{ id: 2, value: 2, isHidden: true },
	{ id: 3, value: 3, isHidden: true },
	{ id: 4, value: 4, isHidden: true },
	{ id: 5, value: 5, isHidden: true },
	{ id: 6, value: 6, isHidden: true },
	{ id: 7, value: 1, isHidden: true },
	{ id: 8, value: 2, isHidden: true },
	{ id: 9, value: 3, isHidden: true },
	{ id: 10, value: 4, isHidden: true },
	{ id: 11, value: 5, isHidden: true },
	{ id: 12, value: 6, isHidden: true },
];
export const CARDS_18 = [
	{ id: 1, value: 1, isHidden: true },
	{ id: 2, value: 2, isHidden: true },
	{ id: 3, value: 3, isHidden: true },
	{ id: 4, value: 4, isHidden: true },
	{ id: 5, value: 5, isHidden: true },
	{ id: 6, value: 6, isHidden: true },
	{ id: 7, value: 7, isHidden: true },
	{ id: 8, value: 8, isHidden: true },
	{ id: 9, value: 9, isHidden: true },
	{ id: 10, value: 1, isHidden: true },
	{ id: 11, value: 2, isHidden: true },
	{ id: 12, value: 3, isHidden: true },
	{ id: 13, value: 4, isHidden: true },
	{ id: 14, value: 5, isHidden: true },
	{ id: 15, value: 6, isHidden: true },
	{ id: 16, value: 7, isHidden: true },
	{ id: 17, value: 8, isHidden: true },
	{ id: 18, value: 9, isHidden: true },
];
export const CARDS_24 = [
	{ id: 1, value: 1, isHidden: true },
	{ id: 2, value: 2, isHidden: true },
	{ id: 3, value: 3, isHidden: true },
	{ id: 4, value: 4, isHidden: true },
	{ id: 5, value: 5, isHidden: true },
	{ id: 6, value: 6, isHidden: true },
	{ id: 7, value: 7, isHidden: true },
	{ id: 8, value: 8, isHidden: true },
	{ id: 9, value: 9, isHidden: true },
	{ id: 10, value: 10, isHidden: true },
	{ id: 11, value: 11, isHidden: true },
	{ id: 12, value: 12, isHidden: true },
	{ id: 13, value: 1, isHidden: true },
	{ id: 14, value: 2, isHidden: true },
	{ id: 15, value: 3, isHidden: true },
	{ id: 16, value: 4, isHidden: true },
	{ id: 17, value: 5, isHidden: true },
	{ id: 18, value: 6, isHidden: true },
	{ id: 19, value: 7, isHidden: true },
	{ id: 20, value: 8, isHidden: true },
	{ id: 21, value: 9, isHidden: true },
	{ id: 22, value: 10, isHidden: true },
	{ id: 23, value: 11, isHidden: true },
	{ id: 24, value: 12, isHidden: true },
];
